### ISSUE TITLE
Allow for configuring app

### ISSUE THREAD

**Issue by zshzebra** [Rizen54/richweather#2]
Love the project, and hope the community adopts this. I think allowing for configuration of module positions, enabling or disabling modules would be nice, and allow for a default city (if not already).

PS: Sorry for the typos, I wrote this on my phone.

**Comment by Rizen54** [comment]
also are you requesting me to make this or youre gonna code and submit PR?

**Comment by s-atrn** [comment]
thank you for the love, could better elaborate on "dinner configuration" and "enable disable" so that i can implement them in a better way?

**Comment by zshzebra** [comment]
> thank you for the love, could better elaborate on "dinner configuration" and "enable disable" so that i can implement them in a better way?
> 

I updated my issue.

**Comment by s-atrn** [comment]
Sorry but enabling/disabling is something i dont think people would need, if there's some extra info which they dont need, just ignore it. Also for the module positions, softcoding it is a real issue with the paddings and the format. hence if someone is desperate for different positions, they'd code it themselves.
Adding "wontfix" label to the issue.

**Comment by shubhamlav** [comment]
@pyscripter99 @Rizen54 What is a "module" and its position?

**Comment by zshzebra** [comment]
> @pyscripter99 @Rizen54 What is a "module" and its position?
> 

Say the temperature or humidity, so the graphical elements.

**Comment by shubhamlav** [comment]
@pyscripter99 Okay so, what do you mean by position? Do you want to be able to position your icon to the left or right of the text or what exactly?

**Comment by ghost** [comment]
Huh, it should be pretty easy to add a configuration file that changes the order of the elements and sets a default city

**Comment by Heinrich-XIAO** [comment]
> Huh, it should be pretty easy to add a configuration file that changes the order of the elements and sets a default city

What language would it be in? JSON? Pkl? TOML? YML?
I feel like JSON or TOML would work well.

**Comment by Heinrich-XIAO** [comment]
Pkl is very new though as it was made by apple just a few months ago.

**Comment by s-atrn** [comment]
> Huh, it should be pretty easy to add a configuration file that changes the order of the elements and sets a default city

default city is something i can make but i don't wanna work on module positions. thing is that i'd have to go through a bit of hassle to make the config file but i dont feel much people would need it. what i am up for though is to add new themes of arrangements of the modules, maybe something like an octagon or a straight list or other similar themes.

**Comment by ghost** [comment]
module positions would be extremely annoying but module order would be pretty easy, i might get to work on it.

**Comment by ghost** [comment]
> > Huh, it should be pretty easy to add a configuration file that changes the order of the elements and sets a default city
> 
> What language would it be in? JSON? Pkl? TOML? YML? I feel like JSON or TOML would work well.

definetely yaml because thats the best.

**Comment by s-atrn** [comment]
> module positions would be extremely annoying but module order would be pretty easy, i might get to work on it.

Well im a student and when i created richfetch and richweather ive been getting very less time to study. so sure if you wanna work on this, i'll assign you

**Comment by ghost** [comment]
sure ill do it, im a student too but school is for losers

**Comment by s-atrn** [comment]
haha alright

**Comment by ghost** [comment]
ok it kind of works in #3

**Comment by s-atrn** [comment]
Done! Thanks everyone.
